-- vhdl_sim.hs — cabal test-suite entry point for GHDL simulation.
--
-- Runs `make` in the sim/ directory, which compiles the Clash-generated VHDL
-- and the hand-written testbench via GHDL, then executes the simulation.
-- Exits 0 on pass (ghdl stops with status 0 after the PASS assertion).
-- Exits non-zero on any compile or simulation failure.
--
-- Requirements: ghdl and make must be on PATH.
-- The VHDL sources are re-generated by:
--   stack run clash -- Example.Project --vhdl
-- or:
--   cabal run clash -- Example.Project --vhdl
import Prelude
import System.Exit   (exitWith, ExitCode(..))
import System.Process (rawSystem)

main :: IO ()
main = do
    rc <- rawSystem "make" ["-C", "sim", "--no-print-directory"]
    exitWith rc
